name: pipeline backend
on:
    push:
        branches:
             - main

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: check folders and files
              run: |
                echo "checking folders and files....."
                ls -l
                echo "folders and files checked"

            - name: check node version
              run: |
                echo "checking node version....."
                node -v
                echo "node version checked"

   

    deployment:
        runs-on: ubuntu-latest
        #needs: build-and-push
        steps:
             - name: connect via ssh and execute commande
               uses: appleboy/ssh-action@v1
               with:
                  host: ${{ secrets.HOST }}
                  username: user
                  password: ${{ secrets.PASSWORD }}
                  script: ls -l




