name: pipeline backend
on:
    push:
        branches:
             - main

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: check folders and files
              run: |
                echo "checking folders and files....."
                ls -l
                echo "folders and files checked"

            - name: check node version
              run: |
                echo "checking node version....."
                node -v
                echo "node version checked"

    build-and-push:
        runs-on: ubuntu-latest
        needs: test
        steps:

            - name: checkout
              uses: actions/checkout@v4

            - name: build docker image
              run: docker build -t syrina89/back-session7 .
            
           # - #name: login to docker Hub
            #  uses: docker/login-action@v3
             # with:
              #  username: ${{ vars.DOCKERHUB_USERNAME }}
               # password: ${{ secrets.DOCKERHUB_TOKEN }}



