name: pipeline backend
on:
    push:
        branches:
             - main

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: check folders and files
              run: |
                echo "checking folders and files....."
                ls -l
                echo "folders and files checked"

            - name: check node version
              run: |
                echo "checking node version....."
                node -v
                echo "node version checked"

    build-and-push:
        runs-on: ubuntu-latest
        needs: test
        steps:

            - name: checkout
              uses: actions/checkout@v4

            - name: build docker image
              run: docker build -t syrina89/back-session7 .
            
            - name: login to docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ vars.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: push docker image
              run: docker push syrina89/back-session7:latest

            - name: tag image with version number
              run: docker tag syrina89/back-session7 syrina89/back-session7:${{github.run_number}}
    deploy:
      runs-on: ubuntu-latest
      needs: build-and-push
      steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.HOST }}
            username: user
            password: ${{ secrets.PASSWORD }}
            script: |
                cd /home/user/devops-session7/back
                sudo git pull
                sudo docker compose pull
                sudo docker compose up -d --force-recreate --remove-orphans


