name: pipeline backend
on:
    push:
        branches:
             - main

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: check folders and files
              run: |
                echo "checking folders and files....."
                ls -l
                echo "folders and files checked"

            - name: check node version
              run: |
                echo "checking node version....."
                node -v
                echo "node version checked"
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: executing remote ssh commands using password
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.HOST }}
            username: user
            password: ${{ secrets.PASSWORD }}
            port: ${{ secrets.PORT }}
            script: ls -l
