name: pipeline backend
on:
    push:
        branches:
             - main

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: check folders and files
              run: |
                echo "checking folders and files....."
                ls -l
                echo "folders and files checked"

            - name: check node version
              run: |
                echo "checking node version....."
                node -v
                echo "node version checked"

   

    deployment:
        runs-on: ubuntu-latest
        #needs: build-and-push
        steps:
          - name: SSH Debug
            uses: appleboy/ssh-action@v1
            with:
              host: 92.113.146.180
              username: user
              password: vps-123456789
              port: 22
              script: |
                echo "Connexion réussie !"
                echo "User: $(whoami)"
                echo "OS: $(uname -a)"
              debug: true  # Active les logs détaillés
            
