name: pipeline backend
on:
    push:
        branches:
             - main

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: check folders and files
              run: |
                echo "checking folders and files....."
                ls -l
                echo "folders and files checked"

            - name: check node version
              run: |
                echo "checking node version....."
                node -v
                echo "node version checked"

   

    deployment:
        runs-on: ubuntu-latest
        #needs: build-and-push
        steps:
          - name: Commande SSH
            uses: appleboy/ssh-action@v1
            with:
              host: ${{ secrets.SSH_HOST }}      # Adresse IP ou nom d'hôte du serveur
              username: ${{ secrets.SSH_USERNAME }}  # Nom d'utilisateur SSH
              password: ${{ secrets.SSH_PASSWORD }}  # Mot de passe SSH (ou utilisez une clé)
              script: |                          # Commandes à exécuter
                ls -la
                whoami
             


